In [29]:
import cv2
import numpy

In [35]:
im_g = cv2.imread("smallgray.png",0)
#0=Grey scale #1=RGB Scale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [25]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [27]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [37]:
ims=numpy.hstack((im_g,im_g,im_g))


In [39]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182]]


In [42]:
igs = numpy.vstack((im_g,im_g,im_g))

In [44]:
print(igs)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [47]:
lst = numpy.hsplit(igs,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [48]:
lst1 = numpy.vsplit(igs,3)
lst1

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]